# Generated by Django 4.0.6 on 2022-08-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nftcollection',
            options={'verbose_name': 'NFTCollection', 'verbose_name_plural': 'NFTCollections'},
        ),
    ]
