# Generated by Django 4.0.6 on 2022-08-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_nftcollection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcollection',
            name='cardsName',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
